import React, { useState } from 'react';
import { Phone, Edit, Bot, Shield, Loader2 } from 'lucide-react';
import { useEmergency } from '../context/EmergencyContext';

interface AISummaryProps {
  onNavigate: (route: string) => void;
}

export const AISummary: React.FC<AISummaryProps> = ({ onNavigate }) => {
  const { emergencyData, initiateSOSCall, startCallStatusMonitoring } = useEmergency();
  const [isInitiating, setIsInitiating] = useState(false);

  const generateAISummary = (): string => {
    const { situationType, locationName, description, numberOfThreats, callNumber, emergencyContact1, emergencyContact2, coordinates } = emergencyData;
    
    const contactInfo = [emergencyContact1, emergencyContact2].filter(Boolean);
    const additionalContactsText = contactInfo.length > 0 
      ? ` Additional contacts to notify: ${contactInfo.join(', ')}.`
      : '';
    
    const threatInfo = numberOfThreats ? ` Number of individuals involved: ${numberOfThreats}.` : '';
    const locationInfo = locationName || (coordinates ? `${coordinates.lat}, ${coordinates.lng}` : 'Location not available');
    
    return `Emergency reported at ${locationInfo}. Details: ${description}. Immediate response requested. Silent communication system in use - victim may not be able to speak freely.`;
  };

  const handleMakeCall = async () => {
    setIsInitiating(true);
    const success = await initiateSOSCall();
    if (success) {
      startCallStatusMonitoring();
      onNavigate('/chat');
    } else {
      console.error('Failed to initiate SOS call');
      setIsInitiating(false);
    }
  };

  const handleEditMessage = () => {
    onNavigate('/form');
  };

  const aiSummary = generateAISummary();

  return (
    <div className="min-h-screen bg-gray-50 p-4 pb-20">
      <div className="max-w-2xl mx-auto pt-12">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-100 rounded-full mb-4">
            <Bot className="w-8 h-8 text-blue-600" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">AI Summary</h1>
          <p className="text-gray-600">Review what will be communicated to authorities</p>
        </div>

        <div className="space-y-6">
          {/* Message Card */}
          <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
            <div className="flex items-start space-x-4 mb-4">
              <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center flex-shrink-0">
                <Bot className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-gray-900 mb-1">Message to Authorities</h2>
                <p className="text-sm text-gray-500">Generated by WhisprNet AI</p>
              </div>
            </div>

            <div className="bg-gray-50 rounded-lg p-4 mb-6">
              <p className="text-gray-800 leading-relaxed">
                {aiSummary}
              </p>
            </div>

            {/* Details Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-gray-500">Type:</span>
                <span className="ml-2 font-medium text-gray-900">{emergencyData.situationType || 'Not specified'}</span>
              </div>
              <div>
                <span className="text-gray-500">Location:</span>
                <span className="ml-2 font-medium text-gray-900">
                  {emergencyData.locationName || emergencyData.location || 
                    (emergencyData.coordinates 
                      ? `${emergencyData.coordinates.lat}, ${emergencyData.coordinates.lng}`
                      : 'Not available')
                  }
                </span>
              </div>
              <div className="md:col-span-2">
                <span className="text-gray-500">Call Number:</span>
                <span className="ml-2 font-medium text-gray-900">{emergencyData.callNumber}</span>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="space-y-3">
            <button
              onClick={handleMakeCall}
              disabled={isInitiating}
              className="w-full bg-red-600 hover:bg-red-700 active:bg-red-800 disabled:bg-red-400 disabled:cursor-not-allowed text-white text-lg font-semibold py-4 px-6 rounded-2xl shadow-sm transform transition-all duration-200 hover:scale-[1.02] active:scale-[0.98] focus:outline-none focus:ring-4 focus:ring-red-300 disabled:transform-none"
            >
              <div className="flex items-center justify-center space-x-3">
                {isInitiating ? (
                  <Loader2 className="w-5 h-5 animate-spin" />
                ) : (
                  <Phone className="w-5 h-5" />
                )}
                <span>{isInitiating ? 'Initiating Call...' : 'Initiate SOS Call'}</span>
              </div>
            </button>

            <button
              onClick={handleEditMessage}
              disabled={isInitiating}
              className="w-full bg-white hover:bg-gray-50 active:bg-gray-100 disabled:bg-gray-100 disabled:cursor-not-allowed text-gray-700 text-lg font-medium py-4 px-6 rounded-2xl border border-gray-300 shadow-sm transform transition-all duration-200 hover:scale-[1.02] active:scale-[0.98] focus:outline-none focus:ring-4 focus:ring-gray-300 disabled:transform-none"
            >
              <div className="flex items-center justify-center space-x-3">
                <Edit className="w-5 h-5" />
                <span>Edit Message</span>
              </div>
            </button>
          </div>

          {/* Security Notice */}
          <div className="bg-blue-50 rounded-2xl p-6 border border-blue-200">
            <div className="flex items-start space-x-3">
              <Shield className="w-6 h-6 text-blue-600 mt-1 flex-shrink-0" />
              <div>
                <h3 className="text-lg font-semibold text-blue-900 mb-2">Secure Communication</h3>
                <p className="text-blue-800 leading-relaxed">
                  Your message is encrypted and will only be shared with emergency responders. WhisprNet 
                  ensures your privacy while getting you the help you need.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};